/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFindRouteImport } from './routes/_authenticated/find'
import { Route as AuthenticatedCrmIdIndexRouteImport } from './routes/_authenticated/$crmId/index'
import { Route as AuthenticatedCrmIdObjectIdRouteImport } from './routes/_authenticated/$crmId/$objectId'
import { Route as AuthenticatedCrmIdDesignRouteImport } from './routes/_authenticated/$crmId/design'
import { Route as AuthenticatedCrmIdSettingsRouteImport } from './routes/_authenticated/$crmId_.settings'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindRoute = AuthenticatedFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmIdIndexRoute = AuthenticatedCrmIdIndexRouteImport.update({
  id: '/$crmId/',
  path: '/$crmId/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmIdObjectIdRoute =
  AuthenticatedCrmIdObjectIdRouteImport.update({
    id: '/$crmId/$objectId',
    path: '/$crmId/$objectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmIdDesignRoute =
  AuthenticatedCrmIdDesignRouteImport.update({
    id: '/$crmId/design',
    path: '/$crmId/design',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmIdSettingsRoute =
  AuthenticatedCrmIdSettingsRouteImport.update({
    id: '/$crmId_/settings',
    path: '/$crmId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/find': typeof AuthenticatedFindRoute
  '/$crmId/$objectId': typeof AuthenticatedCrmIdObjectIdRoute
  '/$crmId/design': typeof AuthenticatedCrmIdDesignRoute
  '/$crmId/settings': typeof AuthenticatedCrmIdSettingsRoute
  '/$crmId/': typeof AuthenticatedCrmIdIndexRoute
}
export interface FileRoutesByTo {
  '/find': typeof AuthenticatedFindRoute
  '/': typeof AuthenticatedIndexRoute
  '/$crmId/$objectId': typeof AuthenticatedCrmIdObjectIdRoute
  '/$crmId/design': typeof AuthenticatedCrmIdDesignRoute
  '/$crmId/settings': typeof AuthenticatedCrmIdSettingsRoute
  '/$crmId': typeof AuthenticatedCrmIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/find': typeof AuthenticatedFindRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$crmId/$objectId': typeof AuthenticatedCrmIdObjectIdRoute
  '/_authenticated/$crmId/design': typeof AuthenticatedCrmIdDesignRoute
  '/_authenticated/$crmId_/settings': typeof AuthenticatedCrmIdSettingsRoute
  '/_authenticated/$crmId/': typeof AuthenticatedCrmIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find'
    | '/$crmId/$objectId'
    | '/$crmId/design'
    | '/$crmId/settings'
    | '/$crmId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/find'
    | '/'
    | '/$crmId/$objectId'
    | '/$crmId/design'
    | '/$crmId/settings'
    | '/$crmId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/find'
    | '/_authenticated/'
    | '/_authenticated/$crmId/$objectId'
    | '/_authenticated/$crmId/design'
    | '/_authenticated/$crmId_/settings'
    | '/_authenticated/$crmId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/find': {
      id: '/_authenticated/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof AuthenticatedFindRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$crmId/': {
      id: '/_authenticated/$crmId/'
      path: '/$crmId'
      fullPath: '/$crmId/'
      preLoaderRoute: typeof AuthenticatedCrmIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$crmId/$objectId': {
      id: '/_authenticated/$crmId/$objectId'
      path: '/$crmId/$objectId'
      fullPath: '/$crmId/$objectId'
      preLoaderRoute: typeof AuthenticatedCrmIdObjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$crmId/design': {
      id: '/_authenticated/$crmId/design'
      path: '/$crmId/design'
      fullPath: '/$crmId/design'
      preLoaderRoute: typeof AuthenticatedCrmIdDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$crmId_/settings': {
      id: '/_authenticated/$crmId_/settings'
      path: '/$crmId/settings'
      fullPath: '/$crmId/settings'
      preLoaderRoute: typeof AuthenticatedCrmIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFindRoute: typeof AuthenticatedFindRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCrmIdObjectIdRoute: typeof AuthenticatedCrmIdObjectIdRoute
  AuthenticatedCrmIdDesignRoute: typeof AuthenticatedCrmIdDesignRoute
  AuthenticatedCrmIdSettingsRoute: typeof AuthenticatedCrmIdSettingsRoute
  AuthenticatedCrmIdIndexRoute: typeof AuthenticatedCrmIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFindRoute: AuthenticatedFindRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCrmIdObjectIdRoute: AuthenticatedCrmIdObjectIdRoute,
  AuthenticatedCrmIdDesignRoute: AuthenticatedCrmIdDesignRoute,
  AuthenticatedCrmIdSettingsRoute: AuthenticatedCrmIdSettingsRoute,
  AuthenticatedCrmIdIndexRoute: AuthenticatedCrmIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
